// Code generated by tygo. DO NOT EDIT.

//////////
// source: game.go

export interface CreateGameResponse {
  game_id: string;
}
export interface JoinGameRequest {
  game_id: string;
  username: string;
}
export interface JoinGameResponse {
  game_id: string;
  player_id: string;
}
