// Code generated by tygo. DO NOT EDIT.

//////////
// source: action_message.go

export const MessageTypeAction: MessageType = "action";
export const MessageTypeActionError: MessageType = "action_error";
export interface ActionMessage {
  base_message: BaseMessage;
  action: Action;
  target_index?: number /* int */;
  vote?: boolean;
}
export type ActionErrorReason = string;
export const NotAllowed: ActionErrorReason = "Action not allowed";
export const InvalidTarget: ActionErrorReason = "Targeted player is cannot be targeted for this action";
export const InvalidAction: ActionErrorReason = "Invalid action";
export const CouldNotStart: ActionErrorReason = "Could not start game";
export interface ActionErrorMessage {
  BaseMessage: BaseMessage;
  reason: ActionErrorReason;
}

//////////
// source: game_state_message.go

export const MessageTypeGameState: MessageType = "game_state";
export interface GameStateMessage {
  base_message: BaseMessage;
  game_state: GameState;
}

//////////
// source: message.go

export type MessageType = string;
export type Message = any;
export interface BaseMessage {
  type: MessageType;
  sender_id: string;
}
