// Code generated by tygo. DO NOT EDIT.

//////////
// source: action_message.go

export const MessageTypeAction: MessageType = "action";
export const MessageTypeActionError: MessageType = "action_error";
export interface ActionMessage {
  base_message: BaseMessage;
  action: Action;
  target_index?: number /* int */;
  vote?: boolean;
  text?: string;
}
export type ActionErrorReason = string;
export const NotAllowed: ActionErrorReason = "Action not allowed";
export const InvalidTarget: ActionErrorReason = "Targeted player is cannot be targeted for this action";
export const CouldNotStart: ActionErrorReason = "Could not start game";
export interface ActionErrorMessage {
  base_message: BaseMessage;
  reason: ActionErrorReason;
}

//////////
// source: connection_error_message.go

export const MessageTypeConnectionError: MessageType = "connection_error";
export type ConnectionErrorType = number /* int */;
export const ConnectionErrorTypeFatal: ConnectionErrorType = 0;
export const ConnectionErrorTypeGameInvalid: ConnectionErrorType = 1;
export const ConnectionErrorTypePlayerInvalid: ConnectionErrorType = 2;
export const ConnectionErrorTypeServerError: ConnectionErrorType = 3;
export interface ConnectionErrorMessage {
  base_message: BaseMessage;
  reason: string;
  error_type: ConnectionErrorType;
}

//////////
// source: game_state_message.go

export const MessageTypeGameState: MessageType = "game_state";
export interface GameStateMessage {
  base_message: BaseMessage;
  game_state: GameState;
}

//////////
// source: message.go

export type MessageType = string;
export type Message = any;
export interface BaseMessage {
  type: MessageType;
  sender_id: string;
}
