// Code generated by tygo. DO NOT EDIT.

//////////
// source: action.go

export type Action = string;
export const ActionStartGame: Action = "start_game";
export const ActionChatSend: Action = "chat_send";
export const ActionInvestigate: Action = "investigate";
export const ActionSpecialElection: Action = "special_election";
export const ActionPolicyPeek: Action = "policy_peek";
export const ActionExecution: Action = "execution";
export const ActionVote: Action = "vote";
export const ActionNominate: Action = "nominate";
export const ActionLegislate: Action = "legislate";
export const ActionProposeVeto: Action = "propose_veto";
export const ActionApproveVeto: Action = "approve_veto";
export const ActionRejectVeto: Action = "reject_veto";
export const ActionEndTurn: Action = "end_turn";
export const ActionNone: Action = "none";

//////////
// source: board.go

export interface ElectionTracker {
  failed_elections: number /* int */;
  max_failures: number /* int */;
}
export interface Board {
  liberal_policies: number /* int */;
  fascist_policies: number /* int */;
  fascist_slots: number /* int */;
  liberal_slots: number /* int */;
  executive_actions: { [key: number /* int */]: Action};
  election_tracker: ElectionTracker;
  danger_zone_start: number /* int */;
}

//////////
// source: card.go

export type Card = string;
export const CardLiberal: Card = "liberal";
export const CardFascist: Card = "fascist";
export const CardHidden: Card = "hidden";

//////////
// source: game_state.go

export type VoteResult = number /* int */;
export const VotePending: VoteResult = 0;
export const VoteHidden: VoteResult = 1;
export const VoteJa: VoteResult = 2;
export const VoteNein: VoteResult = 3;
export interface ChatEntry {
  sender_id: string;
  sender_name: string;
  text: string;
  sent_at_unix: number /* int64 */;
}
export interface GameState {
  players: Player[];
  deck: Card[];
  discard: Card[];
  board: Board;
  president_index: number /* int */;
  chancellor_index: number /* int */;
  prev_president_index: number /* int */;
  prev_chancellor_index: number /* int */;
  nominee_index: number /* int */;
  phase: GamePhase;
  votes?: VoteResult[];
  pending_action?: Action;
  peeked_cards?: Card[];
  peeker_index?: number /* int */;
  resume_order_index?: number /* int */; // Post special election
  resume_phase?: GamePhase;
  winner?: Team;
  host_id: string;
  chat_history: ChatEntry[];
}

//////////
// source: phase.go

export type GamePhase = string;
export const Setup: GamePhase = "setup"; // TODO
export const Nomination: GamePhase = "nomination";
export const Election: GamePhase = "election";
export const Legislation1: GamePhase = "legislation1";
export const Legislation2: GamePhase = "legislation2";
export const Executive: GamePhase = "executive";
export const GameOver: GamePhase = "game_over";
export const Paused: GamePhase = "paused";

//////////
// source: player.go

export type PlayerRole = string;
export const RoleLiberal: PlayerRole = "liberal";
export const RoleHitler: PlayerRole = "hitler";
export const RoleFascist: PlayerRole = "fascist";
export const RoleHidden: PlayerRole = "hidden";
export const RoleUnassigned: PlayerRole = "unassigned";
export interface Player {
  id: string;
  username: string;
  role: PlayerRole;
  is_executed: boolean;
  is_connected: boolean;
}

//////////
// source: team.go

export type Team = string;
export const TeamUnassigned: Team = "UNASSIGNED";
export const TeamFascist: Team = "FASCISTS";
export const TeamLiberal: Team = "LIBERALS";
